version: "3.9"
services:
  app:
    build: .  
    container_name: python_docker
    volumes:
      - .:/workspace  # 掛載當前目錄到容器內 /workspace
    working_dir: /workspace  # 設置容器內的工作目錄
    stdin_open: true
    tty: true
    command: sh  # 啟動時進入 Shell